version: "3.8"

services:
  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  db:
    mem_limit: 10g
    image: postgres:13.1-alpine
    container_name: postgres_db
    ports:
      - "5434:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=arka
      - POSTGRES_DB=instagram_dm_sender
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_data:/home
  
  pgbouncer:
    image: brainsam/pgbouncer:1.7.2
    environment:
      DB_HOST: db
      DB_USER: postgres           # define credentials
      DB_PASSWORD: arka       # define credentials
      DB_port: 5432
      PGBOUNCER_MAX_CLIENT_CONN: 500      # Increase as needed
      PGBOUNCER_DEFAULT_POOL_SIZE: 100    # Increase as needed
      PGBOUNCER_POOL_MODE: transaction               # define database
      PGBOUNCER_QUERY_WAIT_TIMEOUT: 300
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
    depends_on:
      - db
    ports:
      - 6434:6432    
    
volumes:
  redis_data:
  postgres_data:
