version: "3.8"

services:
  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  db:
    image: postgres:13.1-alpine
    container_name: postgres_db
    ports:
      - "5434:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=arka
      - POSTGRES_DB=instagram_dm_sender
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_data:/home
  
  pgbouncer:
    image: brainsam/pgbouncer:1.7.2
    environment:
      DB_HOST: db
      DB_USER: postgres           # define credentials
      DB_PASSWORD: arka       # define credentials
      DB_port: 5432               # define database
    links:
      - db:db
    ports:
      - 6432:6432    
    
volumes:
  redis_data:
  postgres_data:
